/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import BusinessLayer.ThanhToanBO;
import DataAccessLayer.SanPhamDAO;
import DataTranferObject.GiaoDich;
import DataTranferObject.NhanVien;
import DataTranferObject.SanPham;
import Exception.IdSanPhamNotMatch;
import GiaoDien.pnDetailSanPham.fDetailSanPham;
import java.awt.Color;
import java.awt.Frame;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import sun.java2d.SunGraphicsEnvironment;

/**
 *
 * @author lehuyhung
 */
public class fQuanLyBanHang extends javax.swing.JFrame {

    NhanVien nhanVien;

    /**
     * Creates new form fQuanLyBanHang
     *
     * @param nhanVien
     */
    private pnTabHuyDonHang tabHuyDonHang;

    public void onChangeTienKhachHangDua() {
        tfTienTraLai.setText(Integer.parseInt(this.tfTienKhachDua.getText()) - Integer.parseInt(this.tfTongTien.getText()) + "");

    }

    public fQuanLyBanHang(NhanVien nhanVien) {

        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
       
        this.tfTienKhachDua.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                onChangeTienKhachHangDua();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                onChangeTienKhachHangDua();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                onChangeTienKhachHangDua();
            }
        });

        this.nhanVien = nhanVien;
//        Action delete = new AbstractAction() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                System.out.println("xóa dòng");
//                JTable table = (JTable) e.getSource();
//                int modelRow = Integer.valueOf(e.getActionCommand());
//                ((DefaultTableModel) table.getModel()).removeRow(modelRow);
//            }
//        };
     this.setAlwaysOnTop(false);
     jTabbedPane1.add("Thêm sản phẩm mới", new pnThemSanPhamMoi());
     jTabbedPane1.add("Thống kê", new pnThongKe());
     jTabbedPane1.add("Thêm nhà cung cấp mới", new pnThemNhaCungCap());
    }

    private void clearInput() {
        txtfMaSanPham.setText("");
        tfGiaBanHienTai.setText("");
        tfTenSanPham.setText("");
        spSoLuong.setValue(new Integer(0));
        lbAnhMinhHoa.setIcon(null);
    }

    private void clearBang() {
        DefaultTableModel tm = (DefaultTableModel) tbDanhSachMatHang.getModel();
        for (int i = tbDanhSachMatHang.getRowCount() - 1; i >= 0; i--) {
            tm.removeRow(0);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtfMaSanPham = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfGiaBanHienTai = new javax.swing.JTextField();
        tfTenSanPham = new javax.swing.JTextField();
        btnThemSanPham = new javax.swing.JButton();
        lbSoluong = new javax.swing.JLabel();
        lbAnhMinhHoa = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        btnDetailSanPham = new javax.swing.JButton();
        spSoLuong = new javax.swing.JSpinner();
        btnXoa = new javax.swing.JButton();
        lbBaoLoiSoLuongPhaiKhacKhong = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDanhSachMatHang = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        btnThanhToan = new javax.swing.JButton();
        tfTienKhachDua = new javax.swing.JTextField();
        tfTienTraLai = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfTongTien = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý bán hàng");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);

        txtfMaSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfMaSanPhamActionPerformed(evt);
            }
        });

        jLabel3.setText("mã sản phẩm");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addComponent(txtfMaSanPham)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("tên sản phẩm");

        jLabel8.setText("giá");

        tfTenSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenSanPhamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfGiaBanHienTai, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(tfTenSanPham))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfGiaBanHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnThemSanPham.setText("Xác nhận");
        btnThemSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSanPhamActionPerformed(evt);
            }
        });

        lbSoluong.setText("Số lượng");

        lbAnhMinhHoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhminhhoa/dia-ca-nhac-cd-nhung-ca-khuc-bat-hu-ve-bac-ho-do-pham-phuong-thao-trinh-bay.png"))); // NOI18N
        lbAnhMinhHoa.setText("anhminhoa");

        jButton4.setText("clear thông tin");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnDetailSanPham.setText("Detail");
        btnDetailSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailSanPhamActionPerformed(evt);
            }
        });

        spSoLuong.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spSoLuongStateChanged(evt);
            }
        });

        btnXoa.setText("xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbSoluong)
                                .addGap(42, 42, 42)
                                .addComponent(spSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(btnThemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDetailSanPham))
                                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbBaoLoiSoLuongPhaiKhacKhong, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbAnhMinhHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSoluong)
                    .addComponent(spSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbBaoLoiSoLuongPhaiKhacKhong, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbAnhMinhHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(btnDetailSanPham)
                    .addComponent(btnThemSanPham))
                .addGap(14, 14, 14)
                .addComponent(btnXoa))
        );

        jPanel9.setName("danh sách mặt hàng"); // NOI18N

        jLabel4.setText("Danh sách mặt hàng");

        tbDanhSachMatHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbDanhSachMatHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "mã sản phẩm", "tên sản phẩm", "số lượng", "giá", "tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDanhSachMatHang.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbDanhSachMatHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDanhSachMatHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDanhSachMatHang);

        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        tfTienKhachDua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTienKhachDuaActionPerformed(evt);
            }
        });

        tfTienTraLai.setEditable(false);
        tfTienTraLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTienTraLaiActionPerformed(evt);
            }
        });

        jLabel2.setText("tiền khách đưa");

        jLabel5.setText("tiền trả lại");

        jLabel7.setText("tổng tiền");

        tfTongTien.setEditable(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnThanhToan))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTongTien)
                            .addComponent(tfTienKhachDua)
                            .addComponent(tfTienTraLai, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTienTraLai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThanhToan))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(189, 189, 189))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("thêm giao dịch", jPanel2);

        jMenu1.setText("Admin");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lí kho");

        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tfTenSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenSanPhamActionPerformed

    private void txtfMaSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfMaSanPhamActionPerformed

        this.txtfMaSanPham.setBackground(Color.white);
        String idsanpham = this.txtfMaSanPham.getText();
        SanPham sanpham;

        try {
            sanpham = SanPhamDAO.getSanPhamDetail(idsanpham);
            this.tfTenSanPham.setText(sanpham.getTensanpham());
            this.tfGiaBanHienTai.setText("" + sanpham.getGiabanhientai());

            lbAnhMinhHoa.setIcon(new javax.swing.ImageIcon((new javax.swing.ImageIcon("/home/vhk/PROJECT_ON_GIT/mediaoneteam/scr/anhminhhoa/dia-ca-nhac-cd-nhung-ca-khuc-bat-hu-ve-bac-ho-do-pham-phuong-thao-trinh-bay.png")).getImage().getScaledInstance(lbAnhMinhHoa.getWidth(), lbAnhMinhHoa.getHeight(), 2)));

        } catch (IdSanPhamNotMatch ex) {
            this.txtfMaSanPham.setBackground(Color.red);
        }

    }//GEN-LAST:event_txtfMaSanPhamActionPerformed

    private void tfTienKhachDuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTienKhachDuaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tfTienKhachDuaActionPerformed

    private void tfTienTraLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTienTraLaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTienTraLaiActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        //validate
        if (this.tfTienTraLai.getText().equals("") || Integer.parseInt(this.tfTienTraLai.getText()) < 0) {
            JOptionPane.showMessageDialog(this, "lượng tiền khách đưa không đủ");
            return;
        }

        // lấy dữ liệu
        NhanVien nhanVien = this.nhanVien;

        ArrayList<GiaoDich> giaodichs = new ArrayList<GiaoDich>();
        DefaultTableModel dm = (DefaultTableModel) this.tbDanhSachMatHang.getModel();
        int rowCount = dm.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            String idsanpham = dm.getValueAt(i, 0).toString();
            int soluong = Integer.parseInt(dm.getValueAt(i, 2).toString());
            int gia = Integer.parseInt(dm.getValueAt(i, 3).toString());

            giaodichs.add(new GiaoDich(idsanpham, soluong, gia));

        }
        try {
            //gọi message
            ThanhToanBO.thanhToan(nhanVien, giaodichs);
        } catch (IdSanPhamNotMatch ex) {
            Logger.getLogger(fQuanLyBanHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        //clear bảng
        clearBang();

    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnThemSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSanPhamActionPerformed
        // TODO add your handling code here:
        if (Integer.parseInt(this.spSoLuong.getValue().toString()) <= 0) {
            JOptionPane.showMessageDialog(this, " Số lượng phải lớn hơn không");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tbDanhSachMatHang.getModel();
        boolean notfound = true;
        int tongtien = 0;
        for (int i = tbDanhSachMatHang.getRowCount() - 1; i >= 0; i--) {

            if (txtfMaSanPham.getText().equals(model.getValueAt(i, 0).toString())) {
                //update số lượng + giá bán
                model.setValueAt(this.spSoLuong.getValue(), i, 2);
                model.setValueAt(this.tfGiaBanHienTai.getText(), i, 3);
                model.setValueAt(Integer.parseInt(this.tfGiaBanHienTai.getText()) * Integer.parseInt(this.spSoLuong.getValue().toString()), i, 4);
                notfound = false;
                break;
            }
            tongtien = tongtien + Integer.parseInt((String) model.getValueAt(i, 4));

        }
        if (notfound == true) {
            model.addRow(new Object[]{txtfMaSanPham.getText(), tfTenSanPham.getText(), spSoLuong.getValue(), tfGiaBanHienTai.getText(), "" + Integer.parseInt(spSoLuong.getValue().toString()) * Integer.parseInt(tfGiaBanHienTai.getText())});
            tongtien = tongtien + Integer.parseInt(spSoLuong.getValue().toString()) * Integer.parseInt(tfGiaBanHienTai.getText());
        }
        clearInput();

        this.tfTongTien.setText(tongtien + "");
    }//GEN-LAST:event_btnThemSanPhamActionPerformed

    private void tbDanhSachMatHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDanhSachMatHangMouseClicked
        // TODO add your handling code here:
        this.txtfMaSanPham.setText(tbDanhSachMatHang.getValueAt(tbDanhSachMatHang.getSelectedRow(), 0).toString());
        this.tfTenSanPham.setText(tbDanhSachMatHang.getValueAt(tbDanhSachMatHang.getSelectedRow(), 1).toString());
        this.spSoLuong.setValue(tbDanhSachMatHang.getValueAt(tbDanhSachMatHang.getSelectedRow(), 2));
        this.tfGiaBanHienTai.setText(tbDanhSachMatHang.getValueAt(tbDanhSachMatHang.getSelectedRow(), 3).toString());
        SanPham sanpham;
        try {
            sanpham = SanPhamDAO.getSanPham(tbDanhSachMatHang.getValueAt(tbDanhSachMatHang.getSelectedRow(), 0).toString());
            lbAnhMinhHoa.setIcon(new javax.swing.ImageIcon((new javax.swing.ImageIcon("src\\anhminhhoa\\" + sanpham.getAnhminhhoa())).getImage().getScaledInstance(lbAnhMinhHoa.getWidth(), lbAnhMinhHoa.getHeight(), 2)));

        } catch (IdSanPhamNotMatch ex) {
            Logger.getLogger(fQuanLyBanHang.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_tbDanhSachMatHangMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbDanhSachMatHang.getModel();

        this.tfTongTien.setText(Integer.parseInt(this.tfTongTien.getText()) - Integer.parseInt(tbDanhSachMatHang.getValueAt(tbDanhSachMatHang.getSelectedRow(), 4).toString()) + "");
        model.removeRow(tbDanhSachMatHang.getSelectedRow());
        clearInput();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        clearInput();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void spSoLuongStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spSoLuongStateChanged
        // TODO add your handling code here:
        this.lbBaoLoiSoLuongPhaiKhacKhong.setText("");
    }//GEN-LAST:event_spSoLuongStateChanged

    private void btnDetailSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailSanPhamActionPerformed
        try {
            // TODO add your handling code here:

            SanPham sanPham = SanPhamDAO.getSanPhamDetail(this.txtfMaSanPham.getText());
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//               
//            }
//        });
            fDetailSanPham f;
            f = new fDetailSanPham(sanPham);
            f.setVisible(true);

        } catch (IdSanPhamNotMatch ex) {
            Logger.getLogger(fQuanLyBanHang.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnDetailSanPhamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fQuanLyBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fQuanLyBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fQuanLyBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fQuanLyBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fQuanLyBanHang(new NhanVien()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetailSanPham;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThemSanPham;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbAnhMinhHoa;
    private javax.swing.JLabel lbBaoLoiSoLuongPhaiKhacKhong;
    private javax.swing.JLabel lbSoluong;
    private javax.swing.JSpinner spSoLuong;
    private javax.swing.JTable tbDanhSachMatHang;
    private javax.swing.JTextField tfGiaBanHienTai;
    private javax.swing.JTextField tfTenSanPham;
    private javax.swing.JTextField tfTienKhachDua;
    private javax.swing.JTextField tfTienTraLai;
    private javax.swing.JTextField tfTongTien;
    private javax.swing.JTextField txtfMaSanPham;
    // End of variables declaration//GEN-END:variables
}
